# Generated by Django 5.2.3 on 2025-11-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
