# Generated by Django 5.2.3 on 2025-11-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_row_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
