# Generated by Django 5.2.3 on 2025-11-09 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_row_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row',
            old_name='table',
            new_name='table_id',
        ),
    ]
