# Generated by Django 5.2.3 on 2025-11-09 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_table_row_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='tab_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='api.tab'),
            preserve_default=False,
        ),
    ]
