# Generated by Django 5.2.3 on 2025-11-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_column_tab_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='table',
            new_name='table_id',
        ),
        migrations.RenameField(
            model_name='tab',
            old_name='table',
            new_name='table_id',
        ),
    ]
