# Generated by Django 5.2.3 on 2026-01-28 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_table_column_table_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='column',
            old_name='tab_id',
            new_name='tab',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='tab',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RemoveField(
            model_name='column',
            name='table_id',
        ),
        migrations.RemoveField(
            model_name='row',
            name='data',
        ),
        migrations.AddField(
            model_name='column',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='row',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CellValue',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_bool', models.BooleanField(default=False, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='api.column')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='api.row')),
            ],
            options={
                'db_table': 'cell_values',
                'indexes': [models.Index(fields=['row', 'column'], name='cell_values_row_id_72cd6c_idx'), models.Index(fields=['column'], name='cell_values_column__dd8fa3_idx')],
                'unique_together': {('row', 'column')},
            },
        ),
    ]
