# Generated by Django 5.2.3 on 2026-04-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_row_options_rename_tab_id_column_tab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
