# Generated by Django 5.2.3 on 2026-04-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
