# Generated by Django 5.2.3 on 2026-04-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tab_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('tab', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tab',
            unique_together={('table', 'name')},
        ),
    ]
