# Generated by Django 5.2.3 on 2026-02-28 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_alter_row_options_rename_tab_id_column_tab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('no_control', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('plantel', models.CharField(max_length=100)),
                ('carrera', models.CharField(choices=[('PROGRAMACION', 'Programacion'), ('ELECTRONICA', 'Electronica'), ('DEO', 'DESARROLLO ORGANIZACIONAL')], max_length=50)),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='api.row')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='api.table')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='students.student')),
            ],
            options={
                'db_table': 'relations',
                'unique_together': {('student', 'table', 'row')},
            },
        ),
    ]
