# Generated by Django 5.2.3 on 2026-04-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='no_control',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
    ]
