# Generated by Django 5.2.3 on 2026-05-08 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0011_alter_tab_label_alter_column_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('clave_empleado', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('plantel', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personal/fotos/')),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('nivel_educativo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_relations', to='personal.personal')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_row_relations', to='api.row')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_table_relations', to='api.table')),
            ],
            options={
                'db_table': 'personal_relations',
                'unique_together': {('personal', 'table', 'row')},
            },
        ),
    ]
